apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: audio-to-text-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-test1
  name: audio-to-text-test1
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: audio-to-text-test1
    weight: 100
  wildcardPolicy: None
