apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: audio-to-text-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-test1
  name: audio-to-text-test1
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: audio-to-text-test1
